{% set version = '2.0-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jade
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/JADE_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/JADE/JADE_{{ version }}.tar.gz
  sha256: b5a2148c2f3a97717c56c057ddef96cf023d623fa0c957c9c6ad3726e16eec68

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-clue
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-clue

test:
  commands:
    - $R -e "library('JADE')"           # [not win]
    - "\"%R%\" -e \"library('JADE')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=JADE
  license: GPL (>= 2)
  summary: 'Cardoso''s JADE algorithm as well as his functions for joint diagonalization are
    ported to R. Also several other blind source separation (BSS) methods, like AMUSE
    and SOBI, and some criteria for performance evaluation of BSS algorithms, are given.
    The package is described in Miettinen, Nordhausen and Taskinen (2017) <doi:10.18637/jss.v076.i02>. '
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: JADE
# Type: Package
# Title: Blind Source Separation Methods Based on Joint Diagonalization and Some BSS Performance Criteria
# Version: 2.0-1
# Date: 2018-03-02
# Author: Klaus Nordhausen, Jean-Francois Cardoso, Jari Miettinen, Hannu Oja, Esa Ollila, Sara Taskinen
# Maintainer: Klaus Nordhausen <klaus.nordhausen@tuwien.ac.at>
# Imports: clue, graphics
# Suggests: ICS, ICSNP
# Description: Cardoso's JADE algorithm as well as his functions for joint diagonalization are ported to R. Also several other blind source separation (BSS) methods, like AMUSE and SOBI, and some criteria for performance evaluation of BSS algorithms, are given. The package is described in Miettinen, Nordhausen and Taskinen (2017) <doi:10.18637/jss.v076.i02>.
# License: GPL (>= 2)
# LazyData: true
# NeedsCompilation: yes
# Packaged: 2018-03-02 12:05:35 UTC; Klaus Nordhausen
# Repository: CRAN
# Date/Publication: 2018-03-02 15:49:31 UTC
