{% set version = "2.0-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-jade
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/JADE_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/JADE/JADE_{{ version }}.tar.gz
  sha256: d4b3d65a33cae454d3ab13343bceabfb3f6b8004ac64ae7bd86dee92a1cd2055

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-clue
  run:
    - r-base
    - r-clue

test:
  commands:
    - $R -e "library('JADE')"           # [not win]
    - "\"%R%\" -e \"library('JADE')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=JADE
  license: GPL-2.0-or-later
  summary: "Cardoso's JADE algorithm as well as his functions for joint diagonalization are ported to R. Also several other blind source separation (BSS) methods, like AMUSE and SOBI, and some criteria for performance evaluation of BSS algorithms, are given. The package is described in Miettinen, Nordhausen and Taskinen
    (2017) <doi:10.18637/jss.v076.i02>. "
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: JADE
# Type: Package
# Title: Blind Source Separation Methods Based on Joint Diagonalization and Some BSS Performance Criteria
# Version: 2.0-2
# Date: 2019-08-19
# Author: Klaus Nordhausen, Jean-Francois Cardoso, Jari Miettinen, Hannu Oja, Esa Ollila, Sara Taskinen
# Maintainer: Klaus Nordhausen <klaus.nordhausen@tuwien.ac.at>
# Imports: clue, graphics
# Suggests: ICS, ICSNP
# Description: Cardoso's JADE algorithm as well as his functions for joint diagonalization are ported to R. Also several other blind source separation (BSS) methods, like AMUSE and SOBI, and some criteria for performance evaluation of BSS algorithms, are given. The package is described in Miettinen, Nordhausen and Taskinen (2017) <doi:10.18637/jss.v076.i02>.
# License: GPL (>= 2)
# LazyData: true
# NeedsCompilation: yes
# Packaged: 2019-08-19 12:20:10 UTC; knordhause
# Repository: CRAN
# Date/Publication: 2019-08-19 13:10:08 UTC
