travis:
  secure:
    BINSTAR_TOKEN: SuEZCwcCRXtaVJT6Q7Pq7tPo+zy4oZr5zLiIviZIpQSwE4KKv6C38S039TRo+BYXpDVD4IXEMTnI5QRuNrirFuBexGdWjIJj3GSWlKTe/XW6yyjpnUWtnRmxhk6Px2f+j0fKNTWeZbCpJGGVe/s60oqUPWN77jg+8dxyP8k4uNuTQ8yiHRFy8l+SSqPLJH9W4FiLLLIrdolVMuduDfRtvOLtsvzTZsNJPDWhw5u+jJ5wAMtfnxjdE6/9QdgvbGf1WfpLpe5U48SEdNcbJMqu9rJZMHRvbrfmpQ6kqQ3UzapjY64VUhehv5PsDvGfN8rfVWsappQOJSQADShGTPNT3X5TvGz3BZLA9sgf67oEBnf1rwe40jbgL2YdZsFjTFbUjMTOZJIZGy9B2VMQh2n5MzbMPPyGcjQ5uZQQ3F8vVpbI1IswunUcxUhdtzVK7MtAq0mPTbFNyLX1jNi92js7Zhc2t58X92+RY200CgSb/bKY40QpnbbWvjYX+rksPJCv75lM6gNInM/MuWFAed7Fg3NZ8RH2xO5Nudc575plzcUdyWcxWb9BeV3UhECCPvA3hAweEWcmizNZr+PE4hdQWghEs1gs6CpdQBFIu8XwSPOl+0ZM8XVyxJ0jz4U5xa/526MvfAsd9Gafaq+EHB3wGyNM8woXpKCUw6sZZ4HdHFI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
