appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: mdQNMknRpANxaED4UNczPZeXC6ndW8kU4qI0q9z0SKRgKUpwopU/N/mead/Dzp6vCN0FGHkyhlIWoaaecU+t16Vkh+EbXxoKq+Vsf7r2srOWRAkjeSY+OEBB22AllkOg8PTqKMclCxI8iz/gvMHGsZk616wcXlfpr7V7zznyAENRefJpcbQiAVTpqNWPjIFFAcXuAe8tKUoElmzvpTcAfR3BoCMf/b0wata7obqhIkaAxi/yuk8PaYXBPEJ0AAEinAXlMnmspCY5OpbrXjBKF2Zr54jZV0HcgPztzRWDjHmcjPQQDVTbQI38jyAYMIpHkhPZGgJMzRDR8Up0AQceslLWRHdIjo3OevT+Qs4ieT26sDdPtD5//v5qHIPPVE6D6avOoZusfs5noOcwgQjcYDQvJphH9fte5uO3pn9phUEVDwmf4UElQ83Qssk1lzniYCtsKPp79JtYgKAvB5GGB3vUf9V4N4vVvQ2cv9Ylz+XHeIZ7xKSmgAuQi8OKXpssqZXWaLDJQRJ1z7lJ+TIGLROecB9b+TLDsVxTs2CM4Bk9nS4KhXcf9JIhgkG4AVKm3oJCV9XAC0eS4PncuIz8DQTV2rZ7Bc9j4DAntreA7GHaSQJMoGFXmUnZcUJU92mHn+dljspKcZn4GV8PsX4qNMs6yjXmk92a+0ARriVOo/g=
conda_forge_output_validation: true
