travis:
  secure:
    BINSTAR_TOKEN: GdqaGIJ+r+3Wk42mAXGlxNp9H9gmO6leVOWhlv7wXDK00dqfjCZdLqSDLWp6qG689FNy9XtkbFMtYWzRduH6IYGKEBQ8GXlcxy0ayyMbflX4ff6Jlq4fJIcRHMwS1xPVaMHDgkkD4BiNyzGiQX2n8ckNpH7qdViJfjKjF6kbqbt6F3qfiXOiv5CnoCHqIdb+nTRFzZiriB3jRjNyDIETC5oHpUh3kszVp1B+VvSp/V/1vVt/pUkVekkuCRXavqnPiEw1yPnq2oOw9LUGuXckUDSO5Q0W87zatf1+Rw5i5xRqMS1ivaAFg5xj/rIhiS2eYJe9umnViKGIJmIzdiYhbjg6C9Sg0HfFq0vB6YTD3r958Ea4z9Fj658jjf7uADQ8Xq+/e5FPH3adYGtcdSu6fxR+fMIa4drILdbPHYomp9jAh66dJzzTOz1HLOTF8XeEpn+ZaKy1nOv7m5LPWhBMd8GZX415GyaUlIpqXY3tmfWYUaqaaAD7zjzGq+/s/KIYD27bgmQZQyHe78dMsgZadjGJvBAaQmMjq/MGdMq58NiL6teeU91WqFghThk6+PqYo314nIMPzcZssziuzuFEUxCd7j/B3bV1zzszwAmKhzKUxChaq5qxp9YWzTcuFPM/wtxXEDGnPSDz8h6pQ4fIk4R21MqzcYaNBGwMjFK9drs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
