travis:
  secure:
    BINSTAR_TOKEN: P8ek/ui6OrvrbeU/tcp8RGWtuloZKx52/s4I6qWedIRZROy3orQbBX5J4OlNyK8b3eEBlUsoLtjJS+yd/MjG2U3nLwIs9IrZ8qzY8Da7nuFRoPscj1zKbexk2pyX4JKIco0ypRXr25oFcaSw52JoqrjP1gyVX8FKIh8oFMC7Fn3jFfT+zH35PQ+O16rVTW8m6c1OCN6nBV93vPXUtbNpq3K0oBs6hEz1iBKqPgjTz4+XginB+Pd+FbRLsQklL9co0dFhE1cs4eJUbjlVs6tjfp0qInh3Zbpo/XDknnlufqkHHPbPn2RAOYAfbudTxokA4KYGfrRuoTn+D1djq58nahlzFdtYv3AUIABf04vWG/HDICKIYlaV656olLNy5vIUTivG2vCrOuzZaBdtivLhBii+XZt6AiK2oS89dNPblKfd15hS+4TqTbM02lgJDAaqHFYAPOLEyjN6vZIRae2iUHKJzpSQHVB0sdVy3QGyepewD5QlFG+X4zzj8duvubQCKU1YeU09YvnFnglITNmcdedVzxz/eRaNImgn4/+aOlZVynXGSWd8PpVpezl4ySCmybbM4gkdU5HMN6cAbaGBI2i1Iu9sLKrIM4ZN/VyZRz//1gf2hx0iLyggC5JL9fTgJBcJRof2zyJkW+xnc5+vkkuPN9d56KxiC6IQ/x2VX+U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
