travis:
  secure:
    BINSTAR_TOKEN: Uh1oQdhXy8UyLociXXgjTEWiPCskmmUlsbc9OzWT/taudSdWpfYil9EaZU7SDN/WgjSnz4pvQYyw19UzEEzPwGxNanXiCefpwYGi7KgJ0DKKtnBjyFSzuIHPaHhLqGnP+ORgt2ys54idWVPY8U9fe33Z5mZb0prs7SvAs6VYiichop034mybWOmCAzl6oOAexJzvfk0hHDocTI9uoFKhz0bp3XwaY9DAeiTlxXiqKGuhK33fjTQzFhcnfmMbN/YlknJF6FfqwJKKLY8xvckUHszhOaYMbnY9Px+QLTwtl20FZ6MZcbEVFge78ro1TmqlfzV33Fhpibwa4DPi47fDyQdT+Y/mEtgZoHyMeR++xeibFbSnTzbeltXNh+zfu+B3kS2HftwNETEiMVYdxOwCeZSq7S0nJ9e+zf+jVG+2KcSSkG6hx4/9cZ4EbaOZkjF3c9gYB0IIpePlWrb7l5kOSBmWoD6vrHqaVQ90eVo8UxdIzFlS8Wo1Rq5qvdpNavtxabxz7lEaSK1EZI3JGEulqu/5lteK9KJrziSPXxjbws98HYJFHFXIY1bYaW7EEvXn6ptnHqb/l4Bo5uW4V5Zh2HxRsJHg0Huls8Si6IQlCcGVWNjeBx3ma2E61tqWFzY5v787xgrIRv0es7AIHnr2XMxAaCb2EDpQWEO/B4fEQDQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
