travis:
  secure:
    BINSTAR_TOKEN: NqVrJyRYmoRXKpU/5I4C+3BIEXPBgSErzGzHs0dqT1NhjWl1QRDww9UMMcs9vDBhrte0RlBYt/ydpDVDsB9dNfLjc1zdhNXWxC/i+6e1cRcwsrm1PMRHo7NPmKfxWKR4jUA8pNd0htdwwdmFm3TpTosZ13fOjV0Q88UGOIjMeOjbcHvu28TMYuXJsfFjj0NBVeGMMU11s/fBFDdRSel6l7LRBYDHLUUyH3J57y/Xp4335BLVd+VTvOsKe4hO/RjYy619j7o0mP7rAq9y1UgDasujMddO1qarpa5KOliUjghlxwzGJpcgO/qi6ELf56FKoZ7ctPlP4RMdWM+n+VMG9xYjGqDZFHc5YMk31DOweORw+O1kEoFcWjwE1W81sPLS7y/nQbfnyMpovK3oqiXBs8s1cA225YmJX630H8l8giLNXl4+OhVSee2kKPXBRoh+iDej7/x6WYvEtK5h0TI9BVG+U3S+tiGDAex0V7GQET6Qbcsm6R4vSzKZ6/P2ghmJCiRxA071yRux9mjQ9KagqTMUQ6xk1ia7cNt2O/Dwh3+Nwhy1zmWHPzqlhw1KXrGj1+dJZGWOq6O3/yEU1ORua92DbHPUy+EaY0naE1lh1hcrR8M6u1rJzaCV4m6Wj4GYa8rtMs6063M3+ncVChIMpPRyTcRUl5cB3atE4Ucnb1w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
