travis:
  secure:
    BINSTAR_TOKEN: DvLEK+qJCNmYvd40WgAU2RlEsa0a/KbXrxL+a8BXYcg8qapXOrEuaYX6TSVIuzBvsP7+3D7slMl8voklxH3jlDmnhmrxKr8bE8iI7MnFV3Em4CPvMYwUiMvI4YzmOwMPS+ydkYpFwk4jAX5uCVyuJ2+xZkIxNDrzqlBGxKRSWGQ/aNf3XTRdYg/bTx6o/B43F3/o2uLfcTvBA60gvEFwT5OowmB8I6Q4FXNxef3J6z84+EOdgrDm1VFxY199grXLObOUsoeCyYPJ1RSQMD8AsxZQanQb7kwYgzPMhig8/jeemWcSeGC+WbI5tiv2j2YE8PVQeZRBysRYBtiMy/+aO5rnSqdFXqqojzwuSczhjkyR67pGyLhTXnfHyTJj1ryCcVrUbUpy/zHc0J26JuYrQr4m3dLDCvTbMWSvweV1Ui7nIFRBcM5+MphPD2W5qxm1eKm6/XFOSxve58PGyqtE5F1IKV/4ZAe5+pMrvkixFZ9gqLUVbUTz5uVWpaRQQjc7nHvyEHh2UfxbcWS2ZyLTAQ3X88CokjUlnaocz14j24sQjnV416/5ajbij0q94PNHJ3IFE6N1ELcJqZbupjuWk/WEaxP8frtZP8C7A4O8Avou7JFzzn7g4z2GzVXSk1lCUhG9I2RWBe9Y8/nVuoZr3hcxJ+/vzrXuXdaQ7mFHLAU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
